#!/usr/bin/env bash
# A Bash script that prints information about subdomains with a unique structure.

function get_sub_info {
  local domain=$1
  local subdomain=$2
  local full_domain="${subdomain}.${domain}"
  local record_info=$(dig +noall +answer ${full_domain} | awk '{print $4, $5}')
  local record_type=$(echo $record_info | awk '{print $1}')
  local record_ip=$(echo $record_info | awk '{print $2}')

  echo "The subdomain ${subdomain} is a ${record_type} record and points to ${record_ip}"
}

domain=$1
subdomain=$2

if [[ -z "$subdomain" ]]; then
  for sub in www lb-01 web-01 web-02; do
    get_sub_info $domain $sub
  done
else
  get_sub_info $domain $subdomain
fi

